# Generated by Django 2.1.2 on 2018-11-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20181117_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theory.Quest'),
        ),
    ]
