# Generated by Django 2.1.2 on 2018-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_answer_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='quest',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
