# Generated by Django 2.1.2 on 2018-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_auto_20181117_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AddField(
            model_name='quest',
            name='desc2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='desc3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='desc4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='desc5',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='desc6',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
