# Generated by Django 4.1 on 2022-11-19 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_tprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprofile',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
