# Generated by Django 4.1 on 2022-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_tprofile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tprofile',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('EC', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics Engg.'), ('EE', 'Electrical Engg.'), ('IC', 'Instrumentation & Control Engg.')], default=True, max_length=255),
        ),
    ]
