# Generated by Django 4.1 on 2022-11-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_leaderboard_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='quiz',
        ),
    ]
