# Generated by Django 4.1 on 2022-11-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizze_lb'),
        ('leaderboard', '0004_remove_leaderboard_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizze'),
        ),
    ]
