# Generated by Django 4.1 on 2022-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizze_lb'),
        ('leaderboard', '0006_remove_leaderboard_quiz_leaderboard_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='quiz',
            field=models.ManyToManyField(to='quiz.quizze'),
        ),
    ]
