# Generated by Django 2.1 on 2018-09-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180903_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
