# Generated by Django 4.1 on 2022-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_profile_rem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rem_time',
            field=models.IntegerField(default=1800),
        ),
    ]
