# Generated by Django 4.1 on 2022-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_sprofile_contact_alter_sprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=255),
        ),
    ]
