# Generated by Django 4.1 on 2022-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_sprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('EC', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics Engg.'), ('EE', 'Electrical Engg.'), ('IC', 'Instrumentation & Control Engg.')], max_length=255),
        ),
    ]
